---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    driver:
      privileged: true
      run_command: init
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[php-wrapper::default]
    attributes: 
      build-essential:
        compile_time: true
